spring:
  config:
    activate:
      on-profile: "local"
  h2:
    console:
      enabled: true # console available on http://localhost:8080/console
      path:
        "/console"
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "user"
    password: "password"
